include: package:pedantic/analysis_options.yaml
linter:
  rules:
    - await_only_futures
analyzer:
  exclude:
    - example/*.reflectable.dart
    - test/*.reflectable.dart
  strong-mode:
    implicit-casts: true