name: dart_json_mapper
version: 1.2.4
description: >
  This package allows programmers to annotate Dart classes in order to
  serialize / deserialize them from / to JSON.
author: Alexander Mazuruk <alexander.mazuruk@gmail.com>
homepage: https://github.com/k-paxian/dart-json-mapper
environment:
  sdk: '>=2.3.1 <3.0.0'
dependencies:
  reflectable: ^2.2.0
  intl: ^0.16.0
dev_dependencies:
  analyzer: ^0.38.5
  build_runner: any
  build_test: any
  test: any