name: dart_json_mapper
version: 1.0.9
description: >
  This package allows programmers to annotate Dart classes in order to
  serialize / deserialize them from / to JSON.
author: Alexander Mazuruk <alexander.mazuruk@gmail.com>
homepage: https://github.com/k-paxian/dart-json-mapper
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  analyzer: ^0.32.5
  reflectable: ^2.0.6
  fixnum: ^0.10.8
  build: ^0.12.7+3
  build_config: ^0.3.0
  build_runner: ^0.10.1+1
  intl: ^0.15.6
dev_dependencies:
  test: ^1.3.0