name: dart_json_mapper
version: 1.1.1
description: >
  This package allows programmers to annotate Dart classes in order to
  serialize / deserialize them from / to JSON.
author: Alexander Mazuruk <alexander.mazuruk@gmail.com>
homepage: https://github.com/k-paxian/dart-json-mapper
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  reflectable: ^2.0.8
  fixnum: ^0.10.8
  intl: ^0.15.6
dev_dependencies:
  analyzer: ^0.33.0
  build_runner: ^1.1.2
  build_test: any
  test: ^1.3.0