name: dart_json_mapper
version: 0.1.3
description: >
  This package allows programmers to annotate Dart classes in order to
  serialize / deserialize them from / to JSON.
author: Alexander Mazuruk <alexander.mazuruk@gmail.com>
homepage: https://github.com/k-paxian/dart-json-mapper
environment:
  sdk: '>=1.12.0 <3.0.0'
dependencies:
  analyzer: ^0.32.0
  reflectable: ^2.0.3
  build: ^0.12.0
  build_config: ^0.3.0
  build_runner: ^0.10.0
  intl: ^0.15.6
dev_dependencies:
  build_test: ^0.10.0
  test: ^1.3.0