name: dart_json_mapper_fixnum
version: 1.0.0
description: >
  This is a dart-json-mapper complementary package
  provides support for https://pub.dev/packages/fixnum types in order to
  serialize / deserialize them from / to JSON.
author: Alexander Mazuruk <alexander.mazuruk@gmail.com>
homepage: https://github.com/k-paxian/dart-json-mapper-fixnum
environment:
  sdk: '>=2.3.1 <3.0.0'
dependencies:
  dart_json_mapper: any
  fixnum: ^0.10.11
dev_dependencies:
  pedantic: ^1.9.0
  build_runner: any
  build_test: any
  test: any