name: dart_json_mapper_mobx
version: 1.2.1
description: >
  This is a dart-json-mapper complementary package
  provides support for MobX classes in order to
  serialize / deserialize them from / to JSON.
homepage: https://github.com/k-paxian/dart-json-mapper/tree/master/adapters/mobx
environment:
  sdk: '>=2.3.1 <3.0.0'
dependencies:
  dart_json_mapper: '>=1.5.6 <3.0.0'
  mobx: ^1.0.2
dev_dependencies:
  reflectable:
  pedantic:
  build_runner:
  build_test:
  test:
#dependency_overrides:
#  dart_json_mapper:
#    path: ../../mapper
