name: dart_json_mapper_mobx
version: 1.0.0
description: >
  This is a dart-json-mapper complementary package
  provides support for http://mobx.pub classes in order to
  serialize / deserialize them from / to JSON.
homepage: https://github.com/k-paxian/dart-json-mapper
environment:
  sdk: '>=2.3.1 <3.0.0'
dependencies:
  dart_json_mapper: '>=1.2.4 <3.0.0'
  mobx: ^0.3.9+3
dev_dependencies:
  pedantic: ^1.9.0
  build_runner: any
  build_test: any
  test: any