name: dart_json_mapper
version: 1.2.10
description: >
  This package allows programmers to annotate Dart classes in order to
  serialize / deserialize them from / to JSON.
homepage: https://github.com/k-paxian/dart-json-mapper
environment:
  sdk: '>=2.6.1 <3.0.0'
dependencies:
  reflectable: ^2.2.1
  intl: ^0.16.0
dev_dependencies:
  pedantic: ^1.9.0
  build_runner: any
  build_test: any
  test: any