name: dart_json_mapper
version: 1.5.9
description: >
  This package allows programmers to annotate Dart classes in order to
  serialize / deserialize them from / to JSON.
homepage: https://github.com/k-paxian/dart-json-mapper
environment:
  sdk: '>=2.6.1 <3.0.0'
dependencies:
  reflectable: ^2.2.4
  intl: ^0.16.1
dev_dependencies:
  pedantic:
  build_runner:
  build_test:
  test:
