targets:
  $default:
    builders:
      reflectable:
        options:
          iterables:
        generate_for:
          - no/files
      dart_json_mapper:
        generate_for:
          - test/starlink/dart_json_mapper/dart_json_mapper_test.dart