name: Publish to Pub.dev

on: push

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish mapper to pub.dev
        run:  |
          cp README.md ./mapper/README.md
          cp -f LICENSE ./mapper/LICENSE
          echo "current dir: $PWD"
      - uses: k-paxian/dart-package-publisher@master
        with:
          # Required:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          # Required:
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          # Optional:
          relativePath: mapper

      - name: Publish mobx adapter to pub.dev
        run:  |
          cp -f ../../LICENSE LICENSE
        working-directory: ./adapters/mobx
      - uses: k-paxian/dart-package-publisher@master
        with:
          # Required:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          # Required:
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          # Optional:
          relativePath: ./adapters/mobx
          
      - name: Publish fixnum adapter to pub.dev
        run:  |
          cp -f ../../LICENSE LICENSE
        working-directory: ./adapters/fixnum
      - uses: k-paxian/dart-package-publisher@master
        with:
          # Required:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          # Required:
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          # Optional:
          relativePath: ./adapters/fixnum          
