name: Publish to Pub.dev

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v1
      - name: Publish to pub.dev
        run:  |
          cp ../README.md README.md
          pub publish --dry-run
        working-directory: ./mapper