name: Publish to Pub.dev

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v1
      - name: Publish mapper to pub.dev
        run:  |
          cp ../README.md README.md
          cp -f ../LICENSE LICENSE
          mkdir -p ~/.pub-cache
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken":"${{ secrets.OAUTH_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.OAUTH_REFRESH_TOKEN }}",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
            "expiration": 1577149838000
          }
          EOF
          pub publish --dry-run
          pub lish -f
        working-directory: ./mapper

      - name: Publish mobx adapter to pub.dev
        run:  |
          cp -f ../../LICENSE LICENSE
          mkdir -p ~/.pub-cache
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken":"${{ secrets.OAUTH_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.OAUTH_REFRESH_TOKEN }}",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
            "expiration": 1577149838000
          }
          EOF
          pub publish --dry-run
          pub lish -f
        working-directory: ./adapters/mobx

      - name: Publish fixnum adapter to pub.dev
        run:  |
          cp -f ../../LICENSE LICENSE
          mkdir -p ~/.pub-cache
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken":"${{ secrets.OAUTH_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.OAUTH_REFRESH_TOKEN }}",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
            "expiration": 1577149838000
          }
          EOF
          pub publish --dry-run
          pub lish -f
        working-directory: ./adapters/fixnum